language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

script:
      - sudo apt-get update && sudo apt-get install oracle-java8-installer
          - java -version

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcozy
        branch: master
        jdk: oraclejdk8
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcozy
        tags: true
        jdk: oraclejdk8
