language: java

sudo: required
dist: trusty

addons:
    apt:
    packages: 
        - oracle-java8-installer



script:
   - sudo apt-get update && sudo apt-get install oracle-java8-installer
   - java -version

jdk:
  - oraclejdk8

install: true

script:
   - echo start installation
   - sudo apt-get update && sudo apt-get install oracle-java8-installer
   - java -version
   - echo java home: $JAVA_HOME

#cache:
#  directories:
#  - $HOME/.m2
  
install:
    - mvn --settings .travis/settings.xml clean install -Psonatype -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcozy
        branch: master
        jdk: oraclejdk8
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/bco.bcozy
        tags: true
        jdk: oraclejdk8
